/**
 * groups-chat.ts — Node gateway that intercepts chat send so agent replies run
 * through the Node dispatcher (CLI **and** API both work), 2026-05-29.
 *
 * Why this exists
 * ---------------
 * Chat/DM/群聊 replies were generated by Python (`shadowflow/api/chat.py` +
 * `_chat_bridge.py`), which only does BYOK direct-to-LLM — it can't spawn the
 * local CLIs (claude/opencode/…) because the CLI transport (`CliCallable`)
 * lives in Node. Node is already the front gateway (all /api/* hit Node first;
 * unmatched ones proxy to Python). So we mount THIS router before
 * proxyFallback and have it own `POST /api/groups/:id/messages`:
 *
 *   1. persist the user message via Python (X-SF-No-Dispatch so Python's own
 *      reply bridge stays quiet — we own the reply now)
 *   2. for each group agent, run `resolveCallable(executor).turn()` — executor
 *      is `cli:<id>` OR `byok:<provider>` OR anthropic-direct, all uniform
 *   3. persist each agent reply via Python (which publishes it on the SSE bus
 *      the browser is already subscribed to)
 *
 * Everything else under /api/groups (history, SSE events, dm-resolve, reactions,
 * briefboard) is NOT defined here, so Express `next()`s and proxyFallback
 * forwards it to Python unchanged.
 *
 * Persistence is delegated to Python (not direct JSON writes) so atomic-write,
 * schema, path-validation and single-writer invariants stay in one process.
 */
import { mkdirSync, statSync } from 'node:fs';
import { isAbsolute, join } from 'node:path';
import { homedir } from 'node:os';
import { Router, type Request, type Response } from 'express';
import { PYTHON_BACKEND_URL } from '../python-backend';
import { resolveCallable } from '../transport/dispatcher';
import { resolveProviderKey } from '../transport/byokKey';
import { isProviderId } from '../transport/api-clients';
import type { ConversationMessage } from '../lib/conversation-types';

const router = Router();

/** Cap fan-out to match Python `_chat_bridge._MAX_FANOUT_AGENTS`. */
const MAX_FANOUT_AGENTS = 5;

interface GroupRecord {
  group_id: string;
  agent_ids?: string[];
  messages?: Array<{ sender_name?: string; sender_kind?: string; content?: string }>;
  kind?: string;
  /** 2026-05-30 — 用户在群设置选的 CLI 工作目录(绝对路径)。空 = 用默认。 */
  workspace_dir?: string;
}
interface AgentRecord {
  agent_id: string;
  name?: string;
  soul?: string;
}

async function pyGet<T>(path: string): Promise<T | null> {
  try {
    const res = await fetch(`${PYTHON_BACKEND_URL}${path}`);
    if (!res.ok) return null;
    const json = (await res.json()) as { data?: T } | T;
    return ((json as { data?: T }).data ?? json) as T;
  } catch {
    return null;
  }
}

/** POST a message into a group via Python; returns the created MessageItem (or null). */
async function pyPostMessage(
  groupId: string,
  body: { content: string; sender_name: string; sender_kind: string },
  opts: { noDispatch?: boolean } = {},
): Promise<unknown> {
  const headers: Record<string, string> = { 'Content-Type': 'application/json' };
  if (opts.noDispatch) headers['X-SF-No-Dispatch'] = '1';
  const res = await fetch(
    `${PYTHON_BACKEND_URL}/api/groups/${encodeURIComponent(groupId)}/messages`,
    { method: 'POST', headers, body: JSON.stringify(body) },
  );
  if (!res.ok) {
    const txt = await res.text().catch(() => '');
    throw new Error(`python persist failed ${res.status}: ${txt}`);
  }
  return res.json().catch(() => null);
}

/** Map persisted group messages → dispatcher history (user/assistant; skip system). */
function toHistory(
  messages: GroupRecord['messages'],
): ConversationMessage[] {
  const out: ConversationMessage[] = [];
  for (const m of messages ?? []) {
    const kind = m.sender_kind ?? 'user';
    if (kind === 'system') continue; // bridge notices aren't model context
    const role = kind === 'agent' ? 'assistant' : 'user';
    const text = typeof m.content === 'string' ? m.content : '';
    if (text) out.push({ role, blocks: [{ kind: 'text', text }] });
  }
  return out;
}

/**
 * Extract clean assistant text from one `text-delta` chunk value.
 *
 * spawner-bridge (CLI/ACP/MCP) forwards each SSE event verbatim as a text-delta
 * whose value is the wire line `event: <name>\ndata: <json>\n\n` — lossless on
 * the wire, but the consumer must re-parse. We pull `data.text` only from
 * `event: text` blocks (NOT `raw`/`usage`/`complete`, which also carry a
 * `text` field). ApiClientCallable (byok) yields clean text already (no
 * `event:` prefix) → passed through unchanged.
 */
function sseWireToText(value: string): string {
  if (!/^event:\s/m.test(value)) return value; // byok clean text
  let out = '';
  for (const block of value.split('\n\n')) {
    let ev = '';
    let data = '';
    for (const line of block.split('\n')) {
      if (line.startsWith('event:')) ev = line.slice(6).trim();
      else if (line.startsWith('data:')) data = line.slice(5).trim();
    }
    if (ev === 'text' && data) {
      try {
        const j = JSON.parse(data) as { text?: unknown };
        if (typeof j.text === 'string') out += j.text;
      } catch {
        /* non-JSON data line — skip */
      }
    }
  }
  return out;
}

/**
 * Resolve the CLI/ACP/MCP working directory (cwd) for a group.
 *
 * Priority (2026-05-30):
 *   1. group.workspace_dir — user-picked absolute path (group settings DirPicker).
 *      Used verbatim if it's an existing absolute directory. The bypassed CLI
 *      can read/write here, so it's the user's explicit choice.
 *   2. Fallback scratch dir OUTSIDE the repo:
 *      `$SHADOWFLOW_CHAT_DIR | ~/.shadowflow-chat`/chat-workspaces/<groupId>.
 *      Previously this lived under the repo (`process.cwd()/.shadowflow/...`),
 *      which let `claude` follow the git root and read the whole ShadowFlow
 *      codebase — `bypassPermissions + cwd-in-repo` is the dangerous combo we
 *      avoid here (see docs/architecture/chat-cli-cwd-and-permissions.md).
 */
function resolveChatWorkspace(groupId: string, userDir?: string): string {
  if (userDir && userDir.trim() && isAbsolute(userDir.trim())) {
    const p = userDir.trim();
    try {
      if (statSync(p).isDirectory()) return p;
    } catch {
      /* user dir gone / unreadable — fall through to default scratch */
    }
  }
  const root = process.env.SHADOWFLOW_CHAT_DIR?.trim() || join(homedir(), '.shadowflow-chat');
  const dir = join(root, 'chat-workspaces', groupId.replace(/[^\w-]/g, '_'));
  try {
    mkdirSync(dir, { recursive: true });
  } catch {
    /* best-effort; spawn will surface a clearer error if it truly can't run */
  }
  return dir;
}

/** Resolve executor → callable opts (key only for byok:/anthropic-direct). */
function resolveExecutorKey(
  executor: string,
  headers: Request['headers'],
): string | undefined {
  if (executor.startsWith('byok:')) {
    const provider = executor.slice(5);
    if (isProviderId(provider)) return resolveProviderKey(provider, headers);
  }
  if (executor === 'anthropic-direct') return resolveProviderKey('anthropic', headers);
  return undefined; // cli:/acp:/mcp: don't need a key
}

/**
 * Background fan-out: generate + persist one reply per group agent.
 * Never throws to the caller (errors become sender_kind='system' notices).
 */
async function runFanout(
  groupId: string,
  executor: string,
  model: string | undefined,
  headers: Request['headers'],
): Promise<void> {
  const apiKey = resolveExecutorKey(executor, headers);

  const group = await pyGet<GroupRecord>(`/api/groups/${encodeURIComponent(groupId)}`);
  if (!group) return;
  // CLI/ACP/MCP need a cwd; byok/anthropic-direct ignore it. Honor the group's
  // user-picked workspace_dir, else a repo-external scratch dir.
  const workspace = resolveChatWorkspace(groupId, group.workspace_dir);
  const agentIds = (group.agent_ids ?? []).slice(0, MAX_FANOUT_AGENTS);
  if (agentIds.length === 0) {
    await pyPostMessage(groupId, {
      content: '[chat] No agents are members of this group.',
      sender_name: 'system',
      sender_kind: 'system',
    }).catch(() => {});
    return;
  }

  for (const agentId of agentIds) {
    // Reload each round so later agents see earlier replies (fan-out semantics).
    const fresh = await pyGet<GroupRecord>(`/api/groups/${encodeURIComponent(groupId)}`);
    const history = toHistory(fresh?.messages);
    const latestUser = [...history].reverse().find((m) => m.role === 'user');
    const prompt =
      latestUser?.blocks.map((b) => (b.kind === 'text' ? b.text : '')).join('') ?? '';

    const agent = await pyGet<AgentRecord>(`/api/agents/${encodeURIComponent(agentId)}`);
    if (!agent) {
      await pyPostMessage(groupId, {
        content: `[chat] Agent '${agentId}' not found.`,
        sender_name: 'system',
        sender_kind: 'system',
      }).catch(() => {});
      continue;
    }
    const agentName = agent.name || agentId;
    const soul = agent.soul ?? '';

    const ctrl = new AbortController();
    let buf = '';
    let errMsg = '';
    try {
      const callable = resolveCallable(executor, { apiKey, model, workspace });
      for await (const chunk of callable.turn({
        system: soul,
        prompt,
        history: history.slice(0, -1), // exclude the just-read latest user (it's the prompt)
        signal: ctrl.signal,
        model,
      })) {
        if (chunk.type === 'text-delta') buf += sseWireToText(chunk.value);
        else if (chunk.type === 'error') {
          errMsg = chunk.error?.message ?? 'stream error';
          break;
        }
      }
    } catch (e) {
      errMsg = e instanceof Error ? e.message : String(e);
    }

    if (errMsg) {
      await pyPostMessage(groupId, {
        content: `[chat] ${agentName} 出错：${errMsg}`,
        sender_name: 'system',
        sender_kind: 'system',
      }).catch(() => {});
      continue;
    }
    const reply = buf.trim();
    if (!reply) {
      await pyPostMessage(groupId, {
        content: `[chat] ${agentName} 返回空回复。`,
        sender_name: 'system',
        sender_kind: 'system',
      }).catch(() => {});
      continue;
    }
    await pyPostMessage(groupId, {
      content: reply,
      sender_name: agentName,
      sender_kind: 'agent',
    }).catch(() => {});
  }
}

/**
 * POST /api/groups/:id/messages — intercept chat send.
 *
 * Persists the user message, returns 201 immediately (front-end已乐观更新),
 * then runs the reply fan-out in the background (replies stream back via the
 * Python SSE bus). Only `sender_kind:'user'` is intercepted for reply
 * generation; non-user writes are persisted and returned as-is.
 */
router.post('/:id/messages', (req: Request, res: Response) => {
  void (async () => {
    const groupId = req.params.id;
    const body = (req.body ?? {}) as {
      content?: string;
      sender_name?: string;
      sender_kind?: string;
      executor?: string;
      model?: string;
    };
    const senderKind = body.sender_kind ?? 'user';
    const content = typeof body.content === 'string' ? body.content : '';

    try {
      // Persist the incoming message via Python. For user messages set the
      // suppress header so Python's own bridge doesn't ALSO reply (we own it).
      const created = await pyPostMessage(
        groupId,
        {
          content,
          sender_name: body.sender_name ?? (senderKind === 'user' ? 'user' : 'agent'),
          sender_kind: senderKind,
        },
        { noDispatch: senderKind === 'user' },
      );
      res.status(201).json(created);
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      res.status(502).json({ error: { code: 'PERSIST_FAILED', message: msg } });
      return;
    }

    // Only user messages trigger an agent reply.
    if (senderKind !== 'user') return;

    const executor =
      typeof body.executor === 'string' && body.executor.trim()
        ? body.executor.trim()
        : 'anthropic-direct';
    const model =
      typeof body.model === 'string' && body.model.trim() ? body.model.trim() : undefined;

    // Fire-and-forget; replies reach the browser via Python SSE.
    void runFanout(groupId, executor, model, req.headers).catch((e) => {
      // eslint-disable-next-line no-console
      console.warn('[groups-chat] fanout failed:', e);
    });
  })();
});

export { router as groupsChatRouter };
export default router;
