/**
 * Icon registry — single source of truth for all UI icons.
 *
 * Why this exists: Windows + Chrome renders Unicode emoji (📊 ⚡ 🎯 …) via
 * Segoe UI Emoji as colourful 3D glyphs that clash with our cool, line-based
 * design language and break the Skin Slot contract (cannot inherit
 * currentColor). This registry maps every emoji that appears in legacy data
 * (node definitions, connector configs, wizard steps, etc.) onto the
 * matching Lucide line icon, and exposes a single <Icon token=... /> that
 * accepts either an emoji or a Lucide name.
 *
 * Usage:
 *   <Icon token={node.icon} size={16} />          // legacy emoji data still works
 *   <Icon token="FileText" size={16} />            // new code uses Lucide names
 *   <Icon token={undefined} fallback={<Plus />} /> // explicit fallback
 *
 * Adding new mappings: extend EMOJI_TO_NAME below. Lucide icons used in JSX
 * elsewhere should also be re-exported via the named import from this file
 * so we keep the icon set discoverable.
 */
import React, { type ReactNode } from 'react';
import {
  // Core composer / chip icons
  Plus,
  Sparkles,
  User,
  Users,
  FileText,
  MessageSquareQuote,
  MessageCircle,
  Workflow,
  BookOpen,
  Target,
  Paperclip,
  Link2,
  Hash,
  Clipboard,
  ClipboardList,
  History,
  ArrowUp,
  ArrowRight,
  // Files / docs
  Folder,
  FolderOpen,
  FolderTree,
  FileEdit,
  Pencil,
  PenLine,
  Scissors,
  // Tools / config
  Settings,
  Wrench,
  Hammer,
  Scale,
  // Data / charts
  BarChart3,
  TrendingUp,
  TrendingDown,
  // Status / alerts
  AlertTriangle,
  Bell,
  Flame,
  Lightbulb,
  Star,
  PartyPopper,
  Siren,
  Shield,
  Lock,
  Unlock,
  Key,
  KeyRound,
  Eye,
  // Lab / research
  FlaskConical,
  Microscope,
  Telescope,
  Satellite,
  // Map / location
  MapPin,
  Pin,
  // Search / view
  Search,
  ZoomIn,
  ZoomOut,
  Ruler,
  // Media
  Music,
  Music2,
  Mic,
  Headphones,
  Clapperboard,
  Drama,
  Palette,
  Megaphone,
  // Time
  Timer,
  AlarmClock,
  Calendar,
  Pause,
  // Health / misc
  Stethoscope,
  Activity,
  Bandage,
  Pill,
  Trash2,
  Rocket,
  Gem,
  Zap,
  Map as MapIcon,
  Gavel,
  ShoppingCart,
  Briefcase,
  Magnet,
  Anchor,
  Phone,
  Smartphone,
  Tv2,
  Radio,
  Dices,
  Gamepad2,
  CalendarDays,
  Volume2,
  Volume1,
  VolumeX,
  Armchair,
  Bed,
  DoorOpen,
  Inbox,
  Send,
  Shuffle,
  Check,
  CheckCircle2,
  Split,
  GitBranch,
  Database,
  Globe,
  Image as ImageIcon,
  Video,
  Box,
  Heart,
  HardDrive,
  Disc,
  Package,
  Ticket,
  Tag,
  Bookmark,
  Camera,
  Moon,
  Sun,
  HardHat,
  Ban,
  Circle,
  CircleDot,
  Brain,
  Maximize2,
  X,
  type LucideIcon,
} from 'lucide-react';

/**
 * Emoji → Lucide name mapping. Keep alphabetised by Lucide name where
 * possible so duplicate emoji can share one canonical icon.
 *
 * IMPORTANT: This MUST stay in sync with the named imports above. If you add
 * a row here, also add the icon to NAME_TO_ICON below (or import it).
 */
const EMOJI_TO_NAME: Record<string, string> = {
  '📊': 'FileText',
  '📋': 'Clipboard',
  '📝': 'Pencil',
  '✏': 'Pencil',
  '✏️': 'Pencil',
  '✍': 'PenLine',
  '✍️': 'PenLine',
  '✂': 'Scissors',
  '✂️': 'Scissors',
  '⚡': 'Sparkles',
  '✨': 'Sparkles',
  '🎯': 'Target',
  '📚': 'BookOpen',
  '📎': 'Paperclip',
  '🔗': 'Link2',
  '⛓': 'Hash',
  '⛓️': 'Hash',
  '🔮': 'History',
  '🚀': 'Rocket',
  '🔥': 'Flame',
  '💡': 'Lightbulb',
  '⭐': 'Star',
  '🌟': 'Star',
  '💎': 'Gem',
  '📈': 'TrendingUp',
  '📉': 'TrendingDown',
  '➕': 'Plus',
  '➡': 'ArrowRight',
  '➡️': 'ArrowRight',
  '🎉': 'PartyPopper',
  '🎨': 'Palette',
  '📁': 'Folder',
  '📂': 'FolderOpen',
  '🗂': 'FolderTree',
  '🗂️': 'FolderTree',
  '📌': 'Pin',
  '📍': 'MapPin',
  '🔍': 'Search',
  '🔎': 'Search',
  '🔒': 'Lock',
  '🔓': 'Unlock',
  '🔑': 'Key',
  '🗝': 'KeyRound',
  '🗝️': 'KeyRound',
  '🔨': 'Hammer',
  '🛠': 'Wrench',
  '🛠️': 'Wrench',
  '🔧': 'Wrench',
  '⚙': 'Settings',
  '⚙️': 'Settings',
  '⚖': 'Scale',
  '⚖️': 'Scale',
  '🩺': 'Stethoscope',
  '🩹': 'Bandage',
  '🧪': 'FlaskConical',
  '🧫': 'FlaskConical',
  '🔬': 'Microscope',
  '🔭': 'Telescope',
  '📡': 'Satellite',
  '💊': 'Pill',
  '💉': 'Pill',
  '🚪': 'DoorOpen',
  '🛏': 'Bed',
  '🛏️': 'Bed',
  '🛋': 'Armchair',
  '🛋️': 'Armchair',
  '🪑': 'Armchair',
  '🛒': 'ShoppingCart',
  '🔔': 'Bell',
  '📢': 'Megaphone',
  '📣': 'Megaphone',
  '🔊': 'Volume2',
  '🔈': 'Volume1',
  '🔇': 'VolumeX',
  '📞': 'Phone',
  '☎': 'Phone',
  '☎️': 'Phone',
  '📱': 'Smartphone',
  '📲': 'Smartphone',
  '📺': 'Tv2',
  '📻': 'Radio',
  '🎙': 'Mic',
  '🎙️': 'Mic',
  '🎤': 'Mic',
  '🎧': 'Headphones',
  '🎵': 'Music',
  '🎶': 'Music2',
  '⏱': 'Timer',
  '⏱️': 'Timer',
  '⏲': 'Timer',
  '⏲️': 'Timer',
  '⏰': 'AlarmClock',
  '🕰': 'AlarmClock',
  '🕰️': 'AlarmClock',
  '⌚': 'AlarmClock',
  '📅': 'Calendar',
  '📆': 'CalendarDays',
  '🗓': 'CalendarDays',
  '🗓️': 'CalendarDays',
  '⏸': 'Pause',
  '⏸️': 'Pause',
  '⚠': 'AlertTriangle',
  '⚠️': 'AlertTriangle',
  '🛡': 'Shield',
  '🛡️': 'Shield',
  '👁': 'Eye',
  '👁️': 'Eye',
  '🎭': 'Drama',
  '🎬': 'Clapperboard',
  '🎮': 'Gamepad2',
  '🎲': 'Dices',
  '🚨': 'Siren',
  '🗑': 'Trash2',
  '🗑️': 'Trash2',
  '🧰': 'Briefcase',
  '🧲': 'Magnet',
  '🪝': 'Anchor',
  '🧑‍⚖': 'Gavel',
  '🧑‍⚖️': 'Gavel',
  '📐': 'Ruler',
  '📏': 'Ruler',
  '🗺': 'Map',
  '🗺️': 'Map',
  '📥': 'Inbox',
  '📤': 'Send',
  '🔀': 'Shuffle',
  '✅': 'CheckCircle2',
  '☑': 'CheckCircle2',
  '☑️': 'CheckCircle2',
  '✔': 'Check',
  '✔️': 'Check',
  '💞': 'Heart',
  '❤': 'Heart',
  '❤️': 'Heart',
  '💕': 'Heart',
  '💖': 'Heart',
  '💗': 'Heart',
  '🌐': 'Globe',
  '💾': 'HardDrive',
  '💿': 'Disc',
  '📦': 'Package',
  '🎫': 'Ticket',
  '🏷': 'Tag',
  '🏷️': 'Tag',
  '🔖': 'Bookmark',
  '⚓': 'Anchor',
  '📸': 'Camera',
  '📷': 'Camera',
  '🎥': 'Video',
  '🌙': 'Moon',
  '☀': 'Sun',
  '☀️': 'Sun',
  '👷': 'HardHat',
  '🚫': 'Ban',
  '⚪': 'Circle',
  '⚫': 'Circle',
  '🔘': 'CircleDot',
  '🟢': 'Circle',
  '🔴': 'Circle',
  '🟡': 'Circle',
  '📄': 'FileText',
  '🧠': 'Brain',
  '⛶': 'Maximize2',
  '❌': 'X',
  '✕': 'X',
  '✗': 'X',
  '×': 'X',
};

const NAME_TO_ICON: Record<string, LucideIcon> = {
  Plus,
  Sparkles,
  User,
  Users,
  FileText,
  MessageSquareQuote,
  MessageCircle,
  Workflow,
  BookOpen,
  Target,
  Paperclip,
  Link2,
  Hash,
  Clipboard,
  ClipboardList,
  History,
  ArrowUp,
  ArrowRight,
  Folder,
  FolderOpen,
  FolderTree,
  FileEdit,
  Pencil,
  PenLine,
  Scissors,
  Settings,
  Wrench,
  Hammer,
  Scale,
  BarChart3,
  TrendingUp,
  TrendingDown,
  AlertTriangle,
  Bell,
  Flame,
  Lightbulb,
  Star,
  PartyPopper,
  Siren,
  Shield,
  Lock,
  Unlock,
  Key,
  KeyRound,
  Eye,
  FlaskConical,
  Microscope,
  Telescope,
  Satellite,
  MapPin,
  Pin,
  Search,
  ZoomIn,
  ZoomOut,
  Ruler,
  Music,
  Music2,
  Mic,
  Headphones,
  Clapperboard,
  Drama,
  Palette,
  Megaphone,
  Timer,
  AlarmClock,
  Calendar,
  CalendarDays,
  Pause,
  Stethoscope,
  Activity,
  Bandage,
  Pill,
  Trash2,
  Rocket,
  Gem,
  Zap,
  Map: MapIcon,
  Gavel,
  ShoppingCart,
  Briefcase,
  Magnet,
  Anchor,
  Phone,
  Smartphone,
  Tv2,
  Radio,
  Dices,
  Gamepad2,
  Volume2,
  Volume1,
  VolumeX,
  Armchair,
  Bed,
  DoorOpen,
  Inbox,
  Send,
  Shuffle,
  Check,
  CheckCircle2,
  Split,
  GitBranch,
  Database,
  Globe,
  Image: ImageIcon,
  Video,
  Box,
  Heart,
  HardDrive,
  Disc,
  Package,
  Ticket,
  Tag,
  Bookmark,
  Camera,
  Moon,
  Sun,
  HardHat,
  Ban,
  Circle,
  CircleDot,
  Brain,
  Maximize2,
  X,
};

/**
 * Resolve an icon token (emoji char OR Lucide name) to the Lucide component.
 * Returns `null` when the token doesn't match anything we know about.
 */
export function resolveIcon(token: string | undefined | null): LucideIcon | null {
  if (!token) return null;
  // Try direct Lucide name first (new code path)
  const direct = NAME_TO_ICON[token];
  if (direct) return direct;
  // Fall back to emoji → name → component (legacy data path)
  const name = EMOJI_TO_NAME[token];
  if (name) return NAME_TO_ICON[name] ?? null;
  return null;
}

interface IconProps {
  /** Either an emoji ("📊") or a Lucide name ("FileText"). */
  token: string | undefined | null;
  /** Pixel size. Defaults to 16 for inline UI. */
  size?: number;
  /** Stroke width. Lucide default is 2; use 1.5 for finer chrome. */
  strokeWidth?: number;
  /** Fallback ReactNode if token doesn't resolve. Defaults to null. */
  fallback?: ReactNode;
  /** Optional className passthrough. */
  className?: string;
  /** Optional style passthrough. */
  style?: React.CSSProperties;
  /** ARIA label; if omitted icon is treated decorative (aria-hidden). */
  ariaLabel?: string;
}

/**
 * Universal icon component. Accepts both emoji strings (legacy) and Lucide
 * names (preferred for new code). Renders `currentColor` so it inherits the
 * parent text colour and works with the Skin Slot contract.
 */
export function Icon({
  token,
  size = 16,
  strokeWidth = 2,
  fallback = null,
  className,
  style,
  ariaLabel,
}: IconProps): ReactNode {
  const Resolved = resolveIcon(token);
  if (!Resolved) return fallback;
  return (
    <Resolved
      size={size}
      strokeWidth={strokeWidth}
      className={className}
      style={style}
      aria-label={ariaLabel}
      aria-hidden={ariaLabel ? undefined : true}
    />
  );
}

// Re-export the most-used Lucide icons so callers can import from one place.
export {
  Plus,
  Sparkles,
  User,
  Users,
  FileText,
  MessageSquareQuote,
  MessageCircle,
  Workflow,
  BookOpen,
  Target,
  Paperclip,
  Link2,
  Hash,
  Clipboard,
  ClipboardList,
  History,
  ArrowUp,
  ArrowRight,
  Settings,
  Wrench,
  Scale,
  AlertTriangle,
  Bell,
  Flame,
  Lightbulb,
  Star,
  Shield,
  Lock,
  Key,
  KeyRound,
  Eye,
  FlaskConical,
  Microscope,
  MapPin,
  Pin,
  Search,
  Music,
  Mic,
  Headphones,
  Clapperboard,
  Drama,
  Palette,
  Megaphone,
  Timer,
  Calendar,
  Pause,
  Stethoscope,
  Activity,
  Trash2,
  Rocket,
  Gem,
  Zap,
  Pencil,
  Hammer,
  ZoomIn,
  ZoomOut,
  Ruler,
  TrendingUp,
  PartyPopper,
  Siren,
  Folder,
  FolderTree,
  FolderOpen,
  Briefcase,
  Magnet,
  PenLine,
  Scissors,
  Telescope,
  Satellite,
  Pill,
  Bandage,
  Gavel,
  ShoppingCart,
  Phone,
  Smartphone,
  Tv2,
  Radio,
  Dices,
  Gamepad2,
  Volume2,
  Armchair,
  Bed,
  DoorOpen,
  AlarmClock,
  CalendarDays,
  Inbox,
  Send,
  Shuffle,
  Check,
  CheckCircle2,
  Split,
  GitBranch,
  Database,
  Globe,
  ImageIcon,
  Video,
  Box,
  Heart,
  HardDrive,
  Disc,
  Package,
  Ticket,
  Tag,
  Bookmark,
  Camera,
  Moon,
  Sun,
  HardHat,
  Ban,
  Circle,
  CircleDot,
  Brain,
  Maximize2,
  X,
};
